doctrine_migrations:
    migrations_paths:
        'App\Shared\Infrastructure\Persistence\Migrations': '%kernel.project_dir%/src/App/Shared/Infrastructure/Persistence/Migrations'
    enable_profiler: false
    organize_migrations: BY_YEAR_AND_MONTH
