doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: App\Modules\Shared\Infrastructure\Persistence\Doctrine\Type\UuidType
            user_email: App\Modules\User\Infrastructure\Persistence\Doctrine\Type\EmailType
            user_password: App\Modules\User\Infrastructure\Persistence\Doctrine\Type\PasswordType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/User/Domain/Entity'
                prefix: 'App\Modules\User\Domain\Entity'
                alias: User

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

#doctrine:
#    dbal:
#        connections:
#            shop_group_1:
#                url: '%env(resolve:DATABASE_1_URL)%'
#                driver: 'pdo_pgsql'
#                server_version: '12.8'
#        types:
#            calculated_rule: App\Calculator\Doctrine\Type\Rule\CalculatedRuleType
#            money_type: App\Calculator\Doctrine\Type\MoneyType
#            generated_report_client: App\Calculator\Doctrine\Type\GeneratedReport\GeneratedReportClientType
#
#    orm:
#        auto_generate_proxy_classes: true
#        default_entity_manager: shop_group_1
#        entity_managers:
#            shop_group_1:
#                connection: shop_group_1
#                naming_strategy: doctrine.orm.naming_strategy.underscore
#                mappings:
#                    Main:
#                        is_bundle: false
#                        type: attribute
#                        dir: '%kernel.project_dir%/src/Calculator/Entity'
#                        prefix: 'App\Calculator\Entity'
#                        alias: app_1
#                    gedmo_tree:
#                        type: annotation
#                        prefix: Gedmo\Tree\Entity
#                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
#                        alias: GedmoTree # (optional) it will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_loggable:
#                        type: annotation
#                        prefix: Gedmo\Loggable\Entity
#                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
#                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
#                        is_bundle: false
#                    GesdinetJWTRefreshTokenBundle: ~
#
#services:
#    Gedmo\Loggable\LoggableListener:
#        class: Gedmo\Loggable\LoggableListener
#        tags:
#            - { name: doctrine.event_subscriber }
