version: '3.8'

services:
    db:
        container_name: blog-db
        build: docker/postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: dbtestblog
        ports:
            - "15435:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgconf:/etc/postgresql
            - pglog:/var/log/postgresql
        networks:
            - blog_network

    php-fpm:
        container_name: blog-php-fpm
        build:
            context: docker/php-fpm
            args:
              DOCKER_PHP_ENABLE_XDEBUG: 'off'
        depends_on:
            - db
        environment:
            - XDEBUG_CONFIG="remote_host=host.docker.internal remote_enable=1"
            - PHP_IDE_CONFIG="serverName=docker-server"
        volumes:
            - ./:/var/www:rw,cached
            - $HOME/.bash_history:/root/.bash_history
        networks:
            - blog_network

    nginx:
        container_name: blog-nginx
        build:
            context: docker/nginx
            args:
                USER_ID: ${UID-1000}
                GROUP_ID: ${GID-1000}
        volumes:
            - ./:/var/www/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/logs:/var/log/nginx
        depends_on:
            - php-fpm
        ports:
            - "88:80"
            - "448:443"
        networks:
            - blog_network

    redis:
        container_name: blog-redis
        build: docker/redis
        restart: always
        ports:
            - "6377:6379"
        volumes:
            - ./docker/redis/data:/data
            - ./docker/redis/conf:/usr/local/etc/redis/redis.conf
        networks:
            - blog_network
        command: ['redis-server', '--appendonly', 'yes']

networks:
    blog_network:

volumes:
    pgdata:
        driver: local
    pgconf:
        driver: local
    pglog:
        driver: local
