api:
    resource: ../src/UI/Http/Rest/Controller/
    type: attribute

admin:
    resource: ../src/UI/Admin/Controller/
    type: attribute
    prefix: /admin
    name_prefix: 'admin_'

front:
    resource: ../src/UI/Front/Controller/
    type: attribute

api_login_check:
    path: /api/auth/token/login