imports:
    - { resource: services/modules/shared/services.yaml }
    - { resource: services/modules/user/services.yaml }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    UI\Http\Rest\:
        resource: '../src/UI/Http/Rest/*'
        exclude: '../src/UI/Http/Rest/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/'
        tags: ['controller.service_arguments']
