imports:
    - { resource: services/modules/shared/services.yaml }
    - { resource: services/modules/user/services.yaml }
    - { resource: services/modules/blog/services.yaml }
    - { resource: services/ui/rest/services.yaml }
    - { resource: services/ui/admin/services.yaml }
    - { resource: services/ui/front/services.yaml }

parameters:
    redis_dsn: '%env(REDIS_DSN)%'

services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Redis:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%redis_dsn%'