services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Shared\:
    resource: '../../../../src/App/Shared/'

  App\Shared\Infrastructure\Persistence\Doctrine\EventListener\FixPostgresSQLDefaultSchemaListener:
    tags:
      - { name: doctrine.event_listener, event: postGenerateSchema }

  App\Shared\Infrastructure\Bus\Command\MessengerCommandBus:
    arguments:
      - '@messenger.bus.command'